/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import LogicaDatos.Datos.Datos;
import LogicaDatos.Datos.HiloSeleccionCliente;
import LogicaDatos.Datos.HiloSeleccionVendedor;
import caguela.Cliente;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;

/**
 *
 * @author rogas
 */
public class Principal_login extends javax.swing.JFrame {

    
    private int intentos = 0;

    /**
     * Creates new form Principal_comprar
     */
    public Principal_login() {
        initComponents();
        cargarPresentacion();
        

    }

    private void cargarPresentacion() {
        // cargar todos los vendedores en un hilo
        new LogicaDatos.Datos.HiloTodosVendedores().start();
        
        try {
            // ponemos todo en blanco
            jPanel1.setVisible(true);
            jPanel1.setBackground(Color.white);
            
            this.getContentPane().setBackground(Color.white);
            this.setResizable(false);

            //  ponemos cabecera y logo al panel
            this.setLocationRelativeTo(null);//  colocarla en el centro de la pantalla
            // personalizamos pantalla
            this.setTitle("BIENVENIDO    Ca' Guela  1.0    la app de los productos gourmet");
            setIconImage(new ImageIcon(getClass().getResource("/img/logo.png")).getImage());

            // cargamos las fotos y las rescalamos
            BufferedImage img1 = ImageIO.read(getClass().getResource("/img/tienda2.jpg"));
            BufferedImage img2 = ImageIO.read(getClass().getResource("/img/tienda.jpg"));
            BufferedImage img3 = ImageIO.read(getClass().getResource("/img/jamon.png"));
            BufferedImage img4 = ImageIO.read(getClass().getResource("/img/arbol.jpg"));
            BufferedImage img5 = ImageIO.read(getClass().getResource("/img/girasoles.jpg"));

            BufferedImage img6 = ImageIO.read(getClass().getResource("/img/icono_salir.jpg"));
            BufferedImage img7 = ImageIO.read(getClass().getResource("/img/iconoAceptar.jpg"));
            BufferedImage img8 = ImageIO.read(getClass().getResource("/img/icono_guardar.png"));

            Image imagen1 = (Image) img1.getScaledInstance(jLabelImagen1.getWidth(), jLabelImagen1.getHeight(), Image.SCALE_SMOOTH);
            Image imagen2 = (Image) img2.getScaledInstance(jLabelImagen2.getWidth(), jLabelImagen2.getHeight(), Image.SCALE_SMOOTH);
            Image imagen3 = (Image) img3.getScaledInstance(jLabelImagen3.getWidth(), jLabelImagen3.getHeight(), Image.SCALE_SMOOTH);
            Image imagen6 = (Image) img6.getScaledInstance((int) (0.2 * jButtonSalir.getWidth()), (int) (0.45 * jButtonSalir.getHeight()), Image.SCALE_SMOOTH);
            Image imagen7 = (Image) img7.getScaledInstance((int) (0.2 * jButtonNuevoUser.getWidth()), (int) (0.45 * jButtonNuevoUser.getHeight()), Image.SCALE_SMOOTH);
            Image imagen8 = (Image) img8.getScaledInstance((int) (0.3 * jButtonLogin1.getWidth()), (int) (0.7 * jButtonLogin1.getHeight()), Image.SCALE_SMOOTH);

            jLabelImagen1.setIcon(new ImageIcon(imagen1));
            jLabelImagen2.setIcon(new ImageIcon(imagen2));
            jLabelImagen3.setIcon(new ImageIcon(imagen3));

            jButtonLogin1.setIcon(new ImageIcon(imagen7));
            jButtonNuevoUser.setIcon(new ImageIcon(imagen8));
            jButtonSalir.setIcon(new ImageIcon(imagen6));

        } catch (IOException ex) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelInfoConexion = new javax.swing.JLabel();
        jTextFieldpswd = new javax.swing.JPasswordField();
        jButtonLogin1 = new javax.swing.JButton();
        jButtonNuevoUser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelImagen1 = new javax.swing.JLabel();
        jLabelImagen2 = new javax.swing.JLabel();
        jLabelImagen3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Introduce tus datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 204, 102));

        jTextFieldUsuario.setForeground(new java.awt.Color(255, 146, 96));

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 51, 51));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 102));
        jLabel1.setText("Usuario(email)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 102));
        jLabel2.setText("contraseña");

        jLabelInfoConexion.setForeground(new java.awt.Color(255, 146, 96));

        jTextFieldpswd.setForeground(new java.awt.Color(255, 146, 96));

        jButtonLogin1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLogin1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonLogin1.setForeground(new java.awt.Color(255, 204, 102));
        jButtonLogin1.setText("Login");
        jButtonLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin1ActionPerformed(evt);
            }
        });

        jButtonNuevoUser.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNuevoUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNuevoUser.setForeground(new java.awt.Color(0, 102, 255));
        jButtonNuevoUser.setText("registrarse...");
        jButtonNuevoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelInfoConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLogin1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUsuario)
                            .addComponent(jTextFieldpswd, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNuevoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldpswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelInfoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNuevoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 102));
        jLabel3.setText("Ca' Guela    ");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 102));
        jLabel4.setText("la app gourmet . .");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelImagen1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelImagen2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jLabelImagen3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin1ActionPerformed
        // consultamos con la base de datos el usuario y contraseña

        String usuario = jTextFieldUsuario.getText();
        String clave = new String(jTextFieldpswd.getPassword());
        Cliente cliente = new Cliente();
        boolean consultaBBDD = false;

        if (!"".equals(usuario) && !"".equals(clave)) {
            // nos devolvera el CLIENTE correspondiente, sino devuelve un CLIENTE nuevo con id=0
            cliente = MetodosWeb.MetodosWeb.login(usuario, clave);
            System.out.println("*********************************"+cliente.getNombre()+cliente.getId());
            consultaBBDD = cliente.getId() > 0;
        }

        // si está registrado
        if (consultaBBDD) {
            // guardamos los datos.            
            LogicaDatos.Datos.Datos.CLIENTE = cliente;          
           
            
            // siendo VENDEDOR, le preguntamos si quiere rol de VENDEDOR o de comprador
            LogicaDatos.Datos.Datos.rolVender = false;
            if (LogicaDatos.Datos.Datos.CLIENTE.isVendedor()) {
                // le preguntamos si quiere usar rol de comprador o isVendedor
                boolean rolVendedor = MetodosEstaticosDialogos.avisoDialogo(this, "Si!, Vender", "No!, Comprar", "Quieres Vender o comprar?");
                LogicaDatos.Datos.Datos.rolVender = rolVendedor;
                
            }
             // para cargar datos del CLIENTE
            new HiloSeleccionCliente(cliente).start();
            // preguntamos que quiere hacer, en funcion de si es comprador o VENDEDOR, hasta que elige algo resultado!=-1
            elegirRol();

        } // si no es correcto damos 3 oportunidades mas.
        else {
            intentos++;
            try {
                sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(Principal_login.class.getName()).log(Level.SEVERE, null, ex);
            }
            jLabelInfoConexion.setText(intentos + " Revise los datos. Intentelo Nuevamente");
            if (intentos == 3) {
                jLabelInfoConexion.setText(intentos + " Revise los datos. Ultimo intento");
            }
            if (intentos > 3) {
                this.dispose();
                MetodosEstaticosDialogos.avisoDialogo(this, "Aceptar", "Se va a cerrar la aplicacion");
                System.exit(0);
            }

        }
    }//GEN-LAST:event_jButtonLogin1ActionPerformed

    private void jButtonNuevoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoUserActionPerformed
        Grafica.Frames.Diaglo_principal_nuevoUser = new Principal_nuevoUser();        
        Grafica.Frames.Diaglo_principal_nuevoUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonNuevoUserActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        MetodosEstaticosDialogos.acercaDe(this);

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        MetodosEstaticosDialogos.acercaDe(this);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal_login().setVisible(true);
        });
    }

    // metodos private
    private void elegirRol() {
        int resultado = -1;
        while (resultado == -1) {
            if (Datos.rolVender) {
                resultado = MetodosEstaticosDialogos.eligeCombo(this, "Aceptar", "Cancelar", Datos.OPCIONES_VENDEDOR);
                System.out.println("*********************************" + Datos.OPCIONES_VENDEDOR[resultado]);
                switch (resultado) {
                    case 0:
                        if(Grafica.Frames.Dialogo_vender_Productos == null){
                        Grafica.Frames.Dialogo_vender_Productos = new Vender_Productos();
                        }
                        Grafica.Frames.Dialogo_vender_Productos.setVisible(true);
                        this.dispose();
                        break;
                    // en este caso coinciden, pero en el futuro podria ser pantalla distinta.        
                    case 1:
                        if(Grafica.Frames.Dialogo_vender_Productos == null){
                        Grafica.Frames.Dialogo_vender_Productos = new Vender_Productos();
                        }
                        Grafica.Frames.Dialogo_vender_Productos.setVisible(true);
                        this.dispose();
                        break;

                    case 2:
                        boolean confirm = MetodosEstaticosDialogos.avisoDialogo(this, "Salir", "Cancelar", "Deseas abandonar la applicacion?");
                        if (confirm) {
                            this.dispose();
                            System.exit(0);
                            break;
                        }

                }

            } else {
                resultado = MetodosEstaticosDialogos.eligeCombo(this, "Aceptar", "Cancelar", Datos.OPCIONES_COMPRADOR);
                System.out.println("*********************************" + Datos.OPCIONES_VENDEDOR[resultado]);
                switch (resultado) {
                    case 0:
                        
                        int opcion = MetodosEstaticosDialogos.dialogoComboEligeVendedor(this);
                        System.out.println("/////////////////////////////// has optado por elegir "+opcion);
                        
                        if(opcion >= 0){
                            
                        Datos.VENDEDOR= Datos.todosVendedores.get(opcion);
                        System.out.println("ha elegido como vendedor para su pedido a "+Datos.VENDEDOR.getNombre());
                        new HiloSeleccionVendedor(Datos.VENDEDOR).start();
                        Grafica.Frames.DialogoNuevoPedido = new Nuevo_pedido();
                        Grafica.Frames.DialogoNuevoPedido.setVisible(true);
                        this.dispose();
                        }
                        break;
                        
                       
                        
                    case 1:
                        Grafica.Frames.Dialogo_revisar_Pedido_Comprador = new Revisar_Pedido_Comprador();
                        Grafica.Frames.Dialogo_revisar_Pedido_Comprador.setVisible(true);
                        this.dispose();
                        break;
                    case 2:
                        boolean result2 = MetodosEstaticosDialogos.avisoDialogo(this, "Salir", "Cancelar", "Deseas abandonar la applicacion? " + resultado);
                        if (result2) {
                            this.dispose();
                            System.exit(0);
                            break;

                        }

                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin1;
    private javax.swing.JButton jButtonNuevoUser;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelImagen1;
    private javax.swing.JLabel jLabelImagen2;
    private javax.swing.JLabel jLabelImagen3;
    private javax.swing.JLabel jLabelInfoConexion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JPasswordField jTextFieldpswd;
    // End of variables declaration//GEN-END:variables
}
